Repository Team-walkies/Walkie-iOS, pull requests merged in 2025-07, with the labels that each got.

#186 [Feat/Fix] #177/#183 - 알 이벤트 알럿 및 로직 구현 / 권한 비허용 바텀시트 노출 로직 수정
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_danger_gray.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_danger_gray.imageset/ic_danger.svg
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_giftEgg.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_giftEgg.imageset/img_giftEgg.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_giftEgg.imageset/img_giftEgg@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_giftEgg.imageset/img_giftEgg@3x.png
  Walkie-iOS/Walkie-iOS/Sources/App/AppDelegate.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/RemoteConfigManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/UserManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Egg/GetEventEggDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/DefaultEggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/EggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/DefaultEggService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/EggService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/EggTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/Entity/Egg/EventEggEntity.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Implementation/DefaultGetEventEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Protocol/GetEventEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Network/Base/URLConstant.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterDetailView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/BottomSheet/WalkieBottomSheet.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/EventModal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/ModalType.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeAlarmBSView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: feat, fix, 🌀아라, 🥬채웅

#188 [Hotfix] #187 - 바텀시트 및 라이브액티비티 이슈 수정
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Sources/App/AppDelegate.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/AppSession.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/LocationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/BottomSheet/WalkieBottomSheet.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggDetailView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggGuideView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: 🌀아라, hotfix

#192 [Hotfix] #191 - 알 선택 버튼 로직 수정
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
Labels: 🌀아라, hotfix

#208 [Feat] #207 - 헬스케어뷰 스켈레톤 구현
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Calendar/DatePickerView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/CircleProgress/CircleProgressSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/HealthCare/HealthCareView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/HealthCare/View/Skeleton/HealthCareCalorieSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/HealthCare/View/Skeleton/HealthCareInfoSkeletonView.swift
Labels: feat, 🌀아라

#209 [Feat/Hotfix] #206, #205 - 닉네임 변경 Domain/Presentation Layer 구현, 알 부화 뷰 dim 영역 디자인 변경사항 및 수정사항 반영
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/MemberTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Enums/MypageItemEnum.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainSettingSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageChangeNicknameView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageMyInformationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageMyInformationViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: feat, 🥬채웅, hotfix
