Repository Team-walkies/Walkie-iOS, pull requests merged in 2025-04, with the labels that each got.

#66 [Fix] #65 - opacity transition 효과 수정
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
Labels: fix, 🥬채웅

#72 [Feat] #68 - 위치 및 신체활동 권한 허용/비허용 플로우 구현
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_motion.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_motion.imageset/ic_motion.svg
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_nav.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_nav.imageset/ic_location.svg
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_alarm_bs.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_alarm_bs.imageset/img_alarm_bs.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_alarm_bs.imageset/img_alarm_bs@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_alarm_bs.imageset/img_alarm_bs@3x.png
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/AppSession.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/LocationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Network/Config/Config.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/Item/HomeAuthItem.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/State/PermissionState.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeAlarmBSView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeAuthBSView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeAuthItemView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/WebView.swift
Labels: feat, 🌀아라

#88 [Fix/Feat] #74 - 홈뷰 권한 로직 비허용 시 모달 ui 수정 / 코디네이터 도입 / 마이페이지 관련 Data Layer 구현
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg.imageset/img_Emptyview.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg.imageset/img_Emptyview@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg.imageset/img_Emptyview@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_bubble.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_bubble.imageset/Frame 1321319397.svg
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_danger.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/ic_danger.imageset/ic_danger.svg
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/AppRoute.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/Coordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/HomeCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/MypageCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/LoginDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/RefreshAccessTokenDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Member/PatchProfileRequestDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Auth/AuthRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Auth/DefaultAuthRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Character/DefaultCharacterRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/MemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/AuthService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/AuthTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/DefaultAuthService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/VO/Auth/AccessTokenVO.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/VO/Auth/RefreshTokenVO.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/VO/Auth/TokenVO.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/BaseUseCase/BaseUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/User/DefaultLogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/User/LogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarItem.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/Item/HomeAlertStruct.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Logout/MypageLogoutView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Complete/OnboardingCompleteView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SpalshView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/HomeScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/MypageScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/TabBarScene.swift
Labels: feat, fix, 🌀아라, 🥬채웅

#89 [Feat] #75/#76 - 카카오, 애플 로그인 및 토큰 재발급 로직 구현
  Walkie-iOS/Project.swift
  Walkie-iOS/Tuist/Package.resolved
  Walkie-iOS/Tuist/Package.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/TokenKeychainManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/UserManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/LoginDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/LoginRequestDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/ReissueDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Auth/SignupRequestDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Member/RecordedSpotDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Auth/AuthRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Auth/DefaultAuthRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/DefaultMemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/MemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/AuthService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/AuthTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/DefaultAuthService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/Reissue/DefaultReissueService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/Reissue/ReissueService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Auth/Reissue/ReissueTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Character/CharacterTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Character/DefaultCharacterService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/DefaultEggService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/EggTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/DefaultMemberService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/MemberService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/MemberTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Review/ReviewService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Review/ReviewTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/VO/Auth/AccessTokenVO.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/VO/Auth/RefreshTokenVO.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Impl/DefaultLoginUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Impl/DefaultLogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Impl/DefaultRecordedSpotUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Impl/DefaultSignupUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Protocol/LoginUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Protocol/LogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Protocol/RecordedSpotUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Protocol/SignupUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/User/DefaultLogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/MoyaProvider+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/Publisher+.swift
  Walkie-iOS/Walkie-iOS/Sources/Network/Base/URLConstant.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageMyInformationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Withdraw/MypageWithdrawView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Complete/OnboardingCompleteView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginUserInfo.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Nickname/NicknameView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Nickname/SignupViewModel.swift
  Walkie-iOS/Walkie-iOS/Walkie-iOS.entitlements
Labels: feat, 🌀아라
