Repository Team-walkies/Walkie-iOS, pull requests merged in 2025-06, with the labels that each got.

#158 [Feat] #157 - 탭바 터치이펙트 적용
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/ButtonStyle+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/HapticManager.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Network/Base/URLConstant.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: feat, 🌀아라

#162 [Release] 1.0.4 배포
  Walkie-iOS/Project.swift
Labels: release

#164 [Fix/Release] #163 -권한 비허용 시 보유한 알이 있는 케이스 수정 및 1.0.5 배포
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Store/StepStatusStore.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
Labels: fix, 🌀아라, release

#175 [Fix] #169 - 권한바텀시트 애니메이션 사라지는 이슈 해결
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/EnvironmentValues+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/BottomSheet/WalkieBottomSheet.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/CTAButton/CTAButton.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Complete/OnboardingCompleteView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/SplashViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Splash/UpdateBSView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: fix, 🌀아라

#179 [Hotfix] #176 - 마이페이지 뷰모델 분리 / 푸시알림 임시 설정 구현 / 사용하지 않는 코디네이터 삭제
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_danger.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_danger.imageset/ic_danger.svg
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/HomeCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/MypageCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Implementation/DefaultHatchEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabTargetViewFactory.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Enums/MypageItemEnum.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainAccountActionButtonsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainItemView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainSettingSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageMyInformationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/MyInformation/MypageMyInformationViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Withdraw/MypageWithdrawView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Withdraw/MypageWithdrawViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/HomeScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/MypageScene.swift
Labels: 🥬채웅, hotfix

#182 [Setting] #181 - fcm 환경 세팅
  Walkie-iOS/.package.resolved
  Walkie-iOS/Project.swift
  Walkie-iOS/Tuist/Package.swift
  Walkie-iOS/Walkie-iOS/Sources/App/AppDelegate.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Const/CharacterLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Const/StringLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Character/GetCharactersDetailDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Character/CharacterRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Character/DefaultCharacterRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/Entity/Character/CharacterDetailEntity.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Character/Implementation/DefaultGetCharactersDetailUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Character/Protocol/GetCharactersDetailUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/ViewModels/CharacterDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/ViewModels/CharacterViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterDetailSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterDetailView.swift
Labels: setting, 🌀아라

#185 [Hotfix] #171 - 로그아웃 시 StepStatusStore 초기화
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/BaseUseCase/BaseUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/User/Impl/DefaultLogoutUserUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
Labels: 🥬채웅, hotfix
