Repository Team-walkies/Walkie-iOS, pull requests merged in 2025-05, with the labels that each got.

#96 [Feat] #93 - 푸시 알림 설정 로직 구현
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Implementation/DefaultCheckStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationView.swift
Labels: feat, 🥬채웅

#100 [Feat] #80 - 알/캐릭터 변경 시 토스트 메시지 구현
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_check_blue.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_check_blue.imageset/ic_check_blue.svg
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_check_gray.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Icons/Icons_basic/ic_check_gray.imageset/ic_check.svg
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/ViewModels/CharacterDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Toast/ToastContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Toast/ToastManager.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/ViewModels/EggDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
Labels: feat, 🥬채웅

#99 [Fix] #95 - AppCoordinator 모달 로직 추가
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggGuideView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Logout/MypageLogoutView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainAccountActionButtonsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
Labels: feat, fix, 🥬채웅, refactor

#102 [Refactor] #101 - 뷰모델 싱글톤으로 관리하도록 수정
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
Labels: 🥬채웅, refactor

#106 [Fix] #105 - 알 부화 감지 로직 연산자 방향 수정
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Implementation/DefaultCheckStepUseCase.swift
Labels: fix, 🥬채웅

#107 [Fix] #104 - 로그인 뷰모델 상태 초기화 로직 추가
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginViewModel.swift
Labels: fix, 🥬채웅

#108 [Fix] #103 - 캘린더 초기 조회 실패 수정
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Character/GetCharactersDetailDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/DefaultEggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/EggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/EggTarget.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/Entity/Character/CharacterDetailEntity.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/Entity/Character/CharacterEntity.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/DefaultEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/ViewModels/CharacterDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/ViewModels/EggDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Withdraw/MypageWithdrawView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/CalendarViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewViewModel.swift
Labels: fix, 🥬채웅

#113 [Feat] #109 - 걸음수 업데이트 및 기타 수정
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/StepManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Egg/GetEggDetailDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Dto/Egg/GetEggListDto.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/DefaultEggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/EggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/DefaultMemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/MemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/DefaultEggService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Egg/EggService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/DefaultMemberService.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Service/Member/MemberService.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/DefaultEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/EggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Implementation/DefaultUpdateEggStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Protocol/UpdateEggStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Implementation/DefaultCheckStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Implementation/DefaultUpdateStepCacheUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Protocol/CheckStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Protocol/UpdateStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/ViewModels/EggDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggDetailView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/CalendarViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewView.swift
Labels: feat, 🥬채웅

#114 [Feat/Fix] #112 - 스팟탐험동안 걸음수 측정 구현 및 QA 반영
  Walkie-iOS/Project.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/UserManager.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewViewModel.swift
Labels: feat, fix, 🌀아라

#119 [Fix] #118 - 홈뷰 기기대응 수정사항 반영
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect1.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect1.imageset/img.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect1.imageset/img@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect1.imageset/img@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect2.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect2.imageset/img-1.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect2.imageset/img@2x-1.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect2.imageset/img@3x-1.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect3.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect3.imageset/img-2.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect3.imageset/img@2x-2.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/img_eggBackEffect3.imageset/img@3x-2.png
  Walkie-iOS/Walkie-iOS/Sources/Const/EggLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/EnvironmentValues+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/Publisher+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/ShimmerModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/SkeletonModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/SkeletonRectangle/SkeletonRect.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeHistoryView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
Labels: fix, 🌀아라

#117 [Feat] #81 - 홈뷰 스켈레톤 구현
  Walkie-iOS/Walkie-iOS/Sources/Extension/ShimmerModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/SkeletonModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/SkeletonRectangle/SkeletonRect.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
Labels: feat, 🌀아라

#120 [Fix] #116 - 알 부화 로직 / UI 레이아웃 수정 / 기타 버그 픽스
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/StepManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/DefaultEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/Implementation/DefaultUpdateEggStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Step/Implementation/DefaultCheckStepUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainAccountActionButtonsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: fix, 🥬채웅

#124 [Feat] #123 - 마이페이지 스켈레톤 구현
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_blue.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_blue.imageset/egg_blue.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_blue.imageset/egg_blue@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_blue.imageset/egg_blue@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_empty.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_empty.imageset/egg_empty.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_empty.imageset/egg_empty@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_empty.imageset/egg_empty@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_green.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_green.imageset/egg_green.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_green.imageset/egg_green@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_green.imageset/egg_green@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_purple.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_purple.imageset/egg_purple.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_purple.imageset/egg_purple@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_purple.imageset/egg_purple@3x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_yellow.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_yellow.imageset/egg_yellow.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_yellow.imageset/egg_yellow@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Main/Home/egg_yellow.imageset/egg_yellow@3x.png
  Walkie-iOS/Walkie-iOS/Sources/Const/EggLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeHistoryView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeStatsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainProfileSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
Labels: feat, 🌀아라

#127 [Feat] #125 - 회원탈퇴 후 재가입 시도 시 모달 구현
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Modal/Modal.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Enums/MypageItemEnum.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainFeedbackButtonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageWebView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
Labels: feat, 🌀아라

#131 [Feat/Fix] #126, #130스팟리뷰 스켈레톤 구현 및 QA 반영
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/PushNotificationManager.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Const/EggLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/DefaultMemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/DefaultEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/Publisher+.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/ShimmerModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/SkeletonModifier.swift
  Walkie-iOS/Walkie-iOS/Sources/Extension/View+.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/SkeletonRectangle/SkeletonRect.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/WebView/WebView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/CalendarViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Item/ReviewItemView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewViewModel.swift
Labels: feat, fix, 🌀아라

#134 [Release] #133 - 1.0.2 배포
  Walkie-iOS/Project.swift
Labels: release

#135 [Feat] #128 - 보유한 알 뷰 스켈레톤 로딩 구현
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg_skeleton.imageset/Contents.json
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg_skeleton.imageset/img_egg_skeleton.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg_skeleton.imageset/img_egg_skeleton@2x.png
  Walkie-iOS/Walkie-iOS/Resources/Assets.xcassets/Characters/Egg/img_egg_skeleton.imageset/img_egg_skeleton@3x.png
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/DefaultEggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Egg/EggRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/DefaultEggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Domain/UseCase/Egg/EggUseCase.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterDetailView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/CTAButton/CTAButton.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/SnackBar/SnackBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TextFields/TextAreaView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/Toast/ToastView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/ViewModels/EggDetailViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/ViewModels/EggViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggDetailView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggGuideView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggSkeletonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainFeedbackButtonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainProfileSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/CalendarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/DayView.swift
Labels: feat, 🥬채웅

#138 [Refactor] #137 - 팩토리 메소드 패턴 및 StateObject 도입으로 싱글톤 구조 개선
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Character/Views/CharacterView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Egg/Views/EggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/HatchEgg/HatchEggView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/AlarmList/AlarmListView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Map/MapView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Login/LoginView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Onboarding/Nickname/NicknameView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Calendar/CalendarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewView.swift
Labels: 🌀아라, refactor

#141 [Fix] #140 - 알 캐릭터 매핑 및 남은 걸음 수 수정
  Walkie-iOS/Walkie-iOS/Sources/Const/CharacterLiterals.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Character/DefaultCharacterRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Data/Repository/Member/DefaultMemberRepository.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/HomeViewModel.swift
Labels: fix, 🥬채웅

#145 [Hotfix] #144 - 캐릭터 매핑 함수 에러 수정
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/Item/ReviewItemView.swift
Labels: 🥬채웅, hotfix

#149 [Refactor] #143 - AppCoordinator 화면 전환 통합
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/Coordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/AppCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Coordinator/CoordinatorImpl/MypageCoordinator.swift
  Walkie-iOS/Walkie-iOS/Sources/App/Manager/DIContainer.swift
  Walkie-iOS/Walkie-iOS/Sources/App/WalkieIOSApp.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Common/TabBar/TabBarView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeHistoryView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Main/Home/View/HomeHistoryViewFactory.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Enums/MypageItemEnum.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainAccountActionButtonsView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainFeedbackButtonView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainItemView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainServiceSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainSettingSectionView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/View/MypageMainView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Main/ViewModel/MypageMainViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/PushNotification/MypagePushNotificationView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Mypage/Withdraw/MypageWithdrawView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewEdit/ReviewWebView.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Review/ReviewViewModel.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/AppScene.swift
  Walkie-iOS/Walkie-iOS/Sources/Presentation/Route/MypageScene.swift
Labels: 🌀아라, refactor
